// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RPCToggleServiceClient is the client API for RPCToggleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCToggleServiceClient interface {
	FindAll(ctx context.Context, in *FindAllReq, opts ...grpc.CallOption) (*FindAllResp, error)
	InsertOne(ctx context.Context, in *InsertOneReq, opts ...grpc.CallOption) (*InsertOneResp, error)
}

type rPCToggleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCToggleServiceClient(cc grpc.ClientConnInterface) RPCToggleServiceClient {
	return &rPCToggleServiceClient{cc}
}

func (c *rPCToggleServiceClient) FindAll(ctx context.Context, in *FindAllReq, opts ...grpc.CallOption) (*FindAllResp, error) {
	out := new(FindAllResp)
	err := c.cc.Invoke(ctx, "/toggle.RPCToggleService/FindAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCToggleServiceClient) InsertOne(ctx context.Context, in *InsertOneReq, opts ...grpc.CallOption) (*InsertOneResp, error) {
	out := new(InsertOneResp)
	err := c.cc.Invoke(ctx, "/toggle.RPCToggleService/InsertOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCToggleServiceServer is the server API for RPCToggleService service.
// All implementations must embed UnimplementedRPCToggleServiceServer
// for forward compatibility
type RPCToggleServiceServer interface {
	FindAll(context.Context, *FindAllReq) (*FindAllResp, error)
	InsertOne(context.Context, *InsertOneReq) (*InsertOneResp, error)
	mustEmbedUnimplementedRPCToggleServiceServer()
}

// UnimplementedRPCToggleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRPCToggleServiceServer struct {
}

func (UnimplementedRPCToggleServiceServer) FindAll(context.Context, *FindAllReq) (*FindAllResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedRPCToggleServiceServer) InsertOne(context.Context, *InsertOneReq) (*InsertOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertOne not implemented")
}
func (UnimplementedRPCToggleServiceServer) mustEmbedUnimplementedRPCToggleServiceServer() {}

// UnsafeRPCToggleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCToggleServiceServer will
// result in compilation errors.
type UnsafeRPCToggleServiceServer interface {
	mustEmbedUnimplementedRPCToggleServiceServer()
}

func RegisterRPCToggleServiceServer(s grpc.ServiceRegistrar, srv RPCToggleServiceServer) {
	s.RegisterService(&_RPCToggleService_serviceDesc, srv)
}

func _RPCToggleService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCToggleServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toggle.RPCToggleService/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCToggleServiceServer).FindAll(ctx, req.(*FindAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCToggleService_InsertOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCToggleServiceServer).InsertOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toggle.RPCToggleService/InsertOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCToggleServiceServer).InsertOne(ctx, req.(*InsertOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCToggleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "toggle.RPCToggleService",
	HandlerType: (*RPCToggleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _RPCToggleService_FindAll_Handler,
		},
		{
			MethodName: "InsertOne",
			Handler:    _RPCToggleService_InsertOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "toggle.proto",
}
