// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v5.29.3
// source: toggle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllReq) Reset() {
	*x = FindAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toggle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllReq) ProtoMessage() {}

func (x *FindAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_toggle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllReq.ProtoReflect.Descriptor instead.
func (*FindAllReq) Descriptor() ([]byte, []int) {
	return file_toggle_proto_rawDescGZIP(), []int{0}
}

type Toggle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name        string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Key         string      `protobuf:"bytes,3,opt,name=key,proto3" json:"key"`
	Description string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	Status      string      `protobuf:"bytes,5,opt,name=status,proto3" json:"status"`
	CreateAt    int64       `protobuf:"varint,6,opt,name=create_at,json=createAt,proto3" json:"create_at"`
	UpdateAt    int64       `protobuf:"varint,7,opt,name=update_at,json=updateAt,proto3" json:"update_at"`
	Audiences   []*Audience `protobuf:"bytes,8,rep,name=audiences,proto3" json:"audiences"`
}

func (x *Toggle) Reset() {
	*x = Toggle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toggle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toggle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toggle) ProtoMessage() {}

func (x *Toggle) ProtoReflect() protoreflect.Message {
	mi := &file_toggle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toggle.ProtoReflect.Descriptor instead.
func (*Toggle) Descriptor() ([]byte, []int) {
	return file_toggle_proto_rawDescGZIP(), []int{1}
}

func (x *Toggle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Toggle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Toggle) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Toggle) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Toggle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Toggle) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Toggle) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *Toggle) GetAudiences() []*Audience {
	if x != nil {
		return x.Audiences
	}
	return nil
}

func (x *Toggle) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (x *Toggle) SetName(v string) {
	if x != nil {
		x.Name = v
	}
}

func (x *Toggle) SetKey(v string) {
	if x != nil {
		x.Key = v
	}
}

func (x *Toggle) SetDescription(v string) {
	if x != nil {
		x.Description = v
	}
}

func (x *Toggle) SetStatus(v string) {
	if x != nil {
		x.Status = v
	}
}

func (x *Toggle) SetCreateAt(v int64) {
	if x != nil {
		x.CreateAt = v
	}
}

func (x *Toggle) SetUpdateAt(v int64) {
	if x != nil {
		x.UpdateAt = v
	}
}

func (x *Toggle) SetAudiences(v []*Audience) {
	if x != nil {
		x.Audiences = v
	}
}

type Audience struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Rules []*Rule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules"`
}

func (x *Audience) Reset() {
	*x = Audience{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toggle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Audience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audience) ProtoMessage() {}

func (x *Audience) ProtoReflect() protoreflect.Message {
	mi := &file_toggle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audience.ProtoReflect.Descriptor instead.
func (*Audience) Descriptor() ([]byte, []int) {
	return file_toggle_proto_rawDescGZIP(), []int{2}
}

func (x *Audience) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Audience) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Audience) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Audience) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (x *Audience) SetName(v string) {
	if x != nil {
		x.Name = v
	}
}

func (x *Audience) SetRules(v []*Rule) {
	if x != nil {
		x.Rules = v
	}
}

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Attribute string `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute"`
	Operator  string `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator"`
	Value     string `protobuf:"bytes,4,opt,name=value,proto3" json:"value"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toggle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_toggle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_toggle_proto_rawDescGZIP(), []int{3}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Rule) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Rule) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Rule) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

func (x *Rule) SetAttribute(v string) {
	if x != nil {
		x.Attribute = v
	}
}

func (x *Rule) SetOperator(v string) {
	if x != nil {
		x.Operator = v
	}
}

func (x *Rule) SetValue(v string) {
	if x != nil {
		x.Value = v
	}
}

type FindAllResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Toggles []*Toggle `protobuf:"bytes,1,rep,name=toggles,proto3" json:"toggles"`
}

func (x *FindAllResp) Reset() {
	*x = FindAllResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toggle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllResp) ProtoMessage() {}

func (x *FindAllResp) ProtoReflect() protoreflect.Message {
	mi := &file_toggle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllResp.ProtoReflect.Descriptor instead.
func (*FindAllResp) Descriptor() ([]byte, []int) {
	return file_toggle_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllResp) GetToggles() []*Toggle {
	if x != nil {
		return x.Toggles
	}
	return nil
}

func (x *FindAllResp) SetToggles(v []*Toggle) {
	if x != nil {
		x.Toggles = v
	}
}

type InsertOneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Toggle *Toggle `protobuf:"bytes,1,opt,name=toggle,proto3" json:"toggle,omitempty"`
}

func (x *InsertOneReq) Reset() {
	*x = InsertOneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toggle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertOneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOneReq) ProtoMessage() {}

func (x *InsertOneReq) ProtoReflect() protoreflect.Message {
	mi := &file_toggle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOneReq.ProtoReflect.Descriptor instead.
func (*InsertOneReq) Descriptor() ([]byte, []int) {
	return file_toggle_proto_rawDescGZIP(), []int{5}
}

func (x *InsertOneReq) GetToggle() *Toggle {
	if x != nil {
		return x.Toggle
	}
	return nil
}

func (x *InsertOneReq) SetToggle(v *Toggle) {
	if x != nil {
		x.Toggle = v
	}
}

type InsertOneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result"`
}

func (x *InsertOneResp) Reset() {
	*x = InsertOneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toggle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertOneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOneResp) ProtoMessage() {}

func (x *InsertOneResp) ProtoReflect() protoreflect.Message {
	mi := &file_toggle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOneResp.ProtoReflect.Descriptor instead.
func (*InsertOneResp) Descriptor() ([]byte, []int) {
	return file_toggle_proto_rawDescGZIP(), []int{6}
}

func (x *InsertOneResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *InsertOneResp) SetResult(v bool) {
	if x != nil {
		x.Result = v
	}
}

var File_toggle_proto protoreflect.FileDescriptor

var file_toggle_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x22, 0xe2, 0x01, 0x0a, 0x06, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x61, 0x75, 0x64,
	0x69, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x09,
	0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x08, 0x41, 0x75, 0x64,
	0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x72, 0x75, 0x6c,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x66, 0x0a,
	0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x07, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x07, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x73, 0x22, 0x36,
	0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x26,
	0x0a, 0x06, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x06,
	0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0x80, 0x01, 0x0a, 0x10, 0x52, 0x50, 0x43, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12,
	0x12, 0x2e, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x09, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x14, 0x2e, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x74, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_toggle_proto_rawDescOnce sync.Once
	file_toggle_proto_rawDescData = file_toggle_proto_rawDesc
)

func file_toggle_proto_rawDescGZIP() []byte {
	file_toggle_proto_rawDescOnce.Do(func() {
		file_toggle_proto_rawDescData = protoimpl.X.CompressGZIP(file_toggle_proto_rawDescData)
	})
	return file_toggle_proto_rawDescData
}

var file_toggle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_toggle_proto_goTypes = []interface{}{
	(*FindAllReq)(nil),    // 0: toggle.FindAllReq
	(*Toggle)(nil),        // 1: toggle.Toggle
	(*Audience)(nil),      // 2: toggle.Audience
	(*Rule)(nil),          // 3: toggle.Rule
	(*FindAllResp)(nil),   // 4: toggle.FindAllResp
	(*InsertOneReq)(nil),  // 5: toggle.InsertOneReq
	(*InsertOneResp)(nil), // 6: toggle.InsertOneResp
}
var file_toggle_proto_depIdxs = []int32{
	2, // 0: toggle.Toggle.audiences:type_name -> toggle.Audience
	3, // 1: toggle.Audience.rules:type_name -> toggle.Rule
	1, // 2: toggle.FindAllResp.toggles:type_name -> toggle.Toggle
	1, // 3: toggle.InsertOneReq.toggle:type_name -> toggle.Toggle
	0, // 4: toggle.RPCToggleService.FindAll:input_type -> toggle.FindAllReq
	5, // 5: toggle.RPCToggleService.InsertOne:input_type -> toggle.InsertOneReq
	4, // 6: toggle.RPCToggleService.FindAll:output_type -> toggle.FindAllResp
	6, // 7: toggle.RPCToggleService.InsertOne:output_type -> toggle.InsertOneResp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_toggle_proto_init() }
func file_toggle_proto_init() {
	if File_toggle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_toggle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toggle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toggle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toggle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Audience); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toggle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toggle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toggle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertOneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toggle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertOneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_toggle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_toggle_proto_goTypes,
		DependencyIndexes: file_toggle_proto_depIdxs,
		MessageInfos:      file_toggle_proto_msgTypes,
	}.Build()
	File_toggle_proto = out.File
	file_toggle_proto_rawDesc = nil
	file_toggle_proto_goTypes = nil
	file_toggle_proto_depIdxs = nil
}
