// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.30.2
// source: toggle.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCToggleServiceClient is the client API for RPCToggleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCToggleServiceClient interface {
	FindAll(ctx context.Context, in *FindAllReq, opts ...grpc.CallOption) (*FindAllResp, error)
}

type rPCToggleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCToggleServiceClient(cc grpc.ClientConnInterface) RPCToggleServiceClient {
	return &rPCToggleServiceClient{cc}
}

func (c *rPCToggleServiceClient) FindAll(ctx context.Context, in *FindAllReq, opts ...grpc.CallOption) (*FindAllResp, error) {
	out := new(FindAllResp)
	err := c.cc.Invoke(ctx, "/toggle.RPCToggleService/FindAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCToggleServiceServer is the server API for RPCToggleService service.
// All implementations must embed UnimplementedRPCToggleServiceServer
// for forward compatibility
type RPCToggleServiceServer interface {
	FindAll(context.Context, *FindAllReq) (*FindAllResp, error)
	mustEmbedUnimplementedRPCToggleServiceServer()
}

// UnimplementedRPCToggleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRPCToggleServiceServer struct {
}

func (UnimplementedRPCToggleServiceServer) FindAll(context.Context, *FindAllReq) (*FindAllResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedRPCToggleServiceServer) mustEmbedUnimplementedRPCToggleServiceServer() {}

// UnsafeRPCToggleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCToggleServiceServer will
// result in compilation errors.
type UnsafeRPCToggleServiceServer interface {
	mustEmbedUnimplementedRPCToggleServiceServer()
}

func RegisterRPCToggleServiceServer(s grpc.ServiceRegistrar, srv RPCToggleServiceServer) {
	s.RegisterService(&RPCToggleService_ServiceDesc, srv)
}

func _RPCToggleService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCToggleServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toggle.RPCToggleService/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCToggleServiceServer).FindAll(ctx, req.(*FindAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCToggleService_ServiceDesc is the grpc.ServiceDesc for RPCToggleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCToggleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "toggle.RPCToggleService",
	HandlerType: (*RPCToggleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _RPCToggleService_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "toggle.proto",
}
